#!/usr/bin/env bash
# Author: authorName
# Date: 2025-12-17
# vim: ft=bash:

# Set script name based on file name.
_whoami="${0##*/}"
_whereami=$(dirname "$0")

# HEREDOCS + READ HELP FUNCTION
function help() {
  read -r -d '' HELP <<-START
    $_whoami

    -i          (install denver)
    -u          (uninstall denver)
    -h|--help   (print help)
    --priv      (make repo private)
    --pub       (make repo public)
    -v          (turn on verbose debugging)

    Usage:

       $_whoami -v -h

    Requirements/Dependencies:

START

  echo ""
  echo "$HELP"
  echo ""
}

# Color terminal printing via associative arrays
declare -A colors
colors[BLACK]=$(tput setaf 0)
colors[RED]=$(tput setaf 1)
colors[GREEN]=$(tput setaf 2)
colors[YELLOW]=$(tput setaf 3)
colors[LIME_YELLOW]=$(tput setaf 190)
colors[POWDER_BLUE]=$(tput setaf 153)
colors[BLUE]=$(tput setaf 4)
colors[MAGENTA]=$(tput setaf 5)
colors[CYAN]=$(tput setaf 6)
colors[WHITE]=$(tput setaf 7)
declare -A styles
styles[BRIGHT]=$(tput bold)
styles[NORMAL]=$(tput sgr0)
styles[BLINK]=$(tput blink)
styles[REVERSE]=$(tput smso)
styles[UNDERLINE]=$(tput smul)

# usage: format, color, style, string
#   pp "%s" color bright "test this cyan color"
function pp() {
  ppargs=($@)
  printable="${ppargs[@]:3}"
  printf $1 "${colors[$2]}${styles[$3]}$printable${styles[NORMAL]}"
}

# Capture Arguements
argc=$#   # total args
argv=($@) # array of args

hide() {
  gh repo edit --visibility private --accept-visibility-change-consequences
}

unhide() {
  gh repo edit --visibility public --accept-visibility-change-consequences

}

install() {

  unhide
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/danshumaker/homebrew-denver/main/install.sh)"
  hide
}
uninstall() {

  unhide
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/danshumaker/homebrew-denver/main/uninstall.sh)"
  hide
}

# Process Commands
for ((j = 0; j < argc; j++)); do
  case ${argv[j]} in
    -h | --help)
      # Function call
      help
      exit
      ;;
    -i)
      install
      ;;
    -u)
      uninstall
      ;;
    --priv)
      hide
      ;;
    --pub)
      unhide
      ;;
    *)
      pp "%s" RED "Invalid Option ${argv[j]}"
      help
      exit
      ;;
  esac
done
